name: shared_layers

description: >
  Shared codebase for all apps in the monorepo. Reusable code within layered architecture (Data/Domain/Presentation).

version: 0.1.0+1
publish_to: none

# =============================
# ENVIRONMENT
# =============================
environment:
  sdk: ^3.10.0
  flutter: ">=3.22.0"

# =============================
# DEPENDENCIES
# =============================
dependencies:
  adapters_for_bloc:
    path: ../../packages/adapters_for_bloc
  adapters_for_firebase:
    path: ../../packages/adapters_for_firebase
  adapters_for_riverpod:
    path: ../../packages/adapters_for_riverpod
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  formz: ^0.8.0
  go_router: ^16.2.0
  meta: ^1.12.0
  shared_core_modules:
    path: ../../packages/shared_core_modules
  shared_utils:
    path: ../../packages/shared_utils
  shared_widgets:
    path: ../../packages/shared_widgets
  validators: ^3.0.0

# =============================
# DEV DEPENDENCIES
# =============================
dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test_api: ^0.7.7
  very_good_analysis: ^10.0.0

# =============================
# FLUTTER CONFIG
# =============================
flutter:
  uses-material-design: true
  generate: true
