name: adapters_for_firebase
description: >
  Single entry-point adapter around Firebase (init, types, gateways, utils).
  Keeps apps/features backend-agnostic and prevents direct Firebase deps
  leakage.

version: 0.1.0+1
publish_to: none

# =============================
# ENVIRONMENT
# =============================
environment:
  flutter: ">=3.22.0"
  sdk: ^3.10.0

# =============================
# DEPENDENCIES
# =============================
dependencies:
  app_bootstrap:
    path: ../app_bootstrap
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  rxdart: ^0.28.0
  shared_core_modules:
    path: ../../packages/shared_core_modules
  shared_layers:
    path: ../../packages/shared_layers

# =============================
# DEV DEPENDENCIES
# =============================
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

# =============================
# FLUTTER CONFIG
# =============================
flutter:
  generate: true
