name: blueprint_on_qubit
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  adapter_for_apps_on_bloc:
    path: ../../packages/adapter_for_apps_on_bloc
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  core:
    path: ../../packages/core
  device_info_plus: ^11.5.0
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  get_it: ^8.2.0
  go_router: ^16.1.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  url_strategy: ^0.3.0

dev_dependencies:
  bloc_test: ^10.0.0
  # dart_code_metrics: ^5.7.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - .env.dev
    - .env.staging
  # generate: true
  uses-material-design: true
