name: app_on_cubit
description: Blueprint app on Cubit/BloC

version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  app_bootstrap:
    path: ../../packages/app_bootstrap
  # Shared BLoC-specific utilities for apps using Cubit/BLoC
  bloc_adapter:
    path: ../../packages/bloc_adapter
  cached_network_image: ^3.4.1
  core:
    path: ../../packages/core
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  features:
    path: ../../packages/features
  firebase_adapter:
    path: ../../packages/firebase_adapter
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  go_router: ^16.1.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5

dev_dependencies:
  bloc_test: ^10.0.0
  # dart_code_metrics: ^5.7.6
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - .env.dev
    - .env.staging
  # generate: true
  uses-material-design: true
  #
