name: blueprint_on_riverpod
description: Blueprint on RiverPod
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  app_bootstrap_and_config:
    path: ../../packages/app_bootstrap_and_config
  core:
    path: ../../packages/core
  firebase_bootstrap_config:
    path: ../../packages/firebase_bootstrap_config
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.1.1
  intl: ^0.20.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - .env.dev
    - .env.staging
  generate: true
  uses-material-design: true
