name: blueprint_on_riverpod
description: Blueprint on RiverPod

version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  app_bootstrap_and_config:
    path: ../../packages/app_bootstrap_and_config
  cached_network_image: ^3.4.1
  core:
    path: ../../packages/core
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  features:
    path: ../../packages/features
  firebase_bootstrap_config:
    path: ../../packages/firebase_bootstrap_config
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  get_storage: ^2.1.1
  go_router: ^16.2.0
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  specific_for_riverpod:
    path: ../../packages/specific_for_riverpod

dev_dependencies:
  build_runner: ^2.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.5
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - .env.dev
    - .env.staging
  generate: true
  uses-material-design: true
