name: core

description: >
  A centralized Flutter package containing the shared codebase for all
  applications in the monorepo. Organized into reusable feature modules
  (Animations, Error Handling, Localization, Navigation, Overlays, Theme, etc.)
  and layered architecture (Data, Domain, Presentation) to ensure consistency,
  maintainability, and rapid development across multiple app variants.

version: 0.1.0+1
publish_to: none
environment:
  sdk: ^3.8.0
  flutter: ">=3.22.0"

dependencies:
  cloud_firestore: ">=6.0.0 <7.0.0"
  collection: ^1.18.0
  dio: ^5.9.0
  easy_localization: ^3.0.5
  equatable: ^2.0.7
  firebase_auth: ">=6.0.1 <7.0.0"
  firebase_core: ">=3.15.2 <5.0.0"
  firebase_crashlytics: ">=5.0.0 <6.0.0"
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  get_it: ^8.2.0
  get_storage: ^2.1.1
  go_router: ^16.1.0
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  logger: ^2.3.0
  meta: ^1.12.0
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.1
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - assets/fonts/
    - assets/translations/
    - assets/images/

  generate: true
  uses-material-design: true

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/sf_fonts/SFProText-Regular.ttf
          weight: 400
        - asset: assets/sf_fonts/SFProText-RegularItalic.ttf
          weight: 400
          style: italic

spider:
  generate_tests: false
  no_comments: true
  export: true
  use_part_of: true
  use_references_list: false

  package: resources
  groups:
    - path: assets/images
      class_name: AppImagesPaths
      types: [.png, .jpg, .jpeg, .webp, .webm, .bmp]
