name: core
description: >
  Shared codebase for all apps in the monorepo. Reusable base modules
  (Animations, Errors, Localization, Navigation, Overlays, Theme, etc.) with
  layered architecture (Data/Domain/Presentation).

version: 0.1.0+1
publish_to: none

# =============================
# ENVIRONMENT
# =============================
environment:
  sdk: ^3.8.0
  flutter: ">=3.22.0"

# =============================
# DEPENDENCIES
# =============================
dependencies:
  bloc_adapter:
    path: ../../packages/bloc_adapter
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  firebase_adapter:
    path: ../../packages/firebase_adapter
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  go_router: ^16.2.0
  meta: ^1.12.0
  riverpod_adapter:
    path: ../../packages/riverpod_adapter
  validators: ^3.0.0

# =============================
# DEV DEPENDENCIES
# =============================
dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

# =============================
# FLUTTER CONFIG
# =============================
flutter:
  uses-material-design: true
  generate: true

  # -----------------------------
  # ASSETS
  # -----------------------------
  assets:
    - assets/fonts/
    - assets/translations/
    - assets/images/

  # -----------------------------
  # FONTS (Inter & Montserrat)
  # -----------------------------
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
