name: features
description: Shared clean-architecture feature modules (domain/data) for all apps
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  cloud_firestore: ^6.0.0
  core:
    path: ../../packages/core
  firebase_auth: ^6.0.1
  firebase_bootstrap_config:
    path: ../../packages/firebase_bootstrap_config
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
