name: specific_for_riverpod
description: Lightweight adapters that connect core ports to Riverpod.

version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  core:
    path: ../core
  firebase_auth: ^6.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
