name: specific_for_riverpod
description: Lightweight adapters that connect core ports to Riverpod.

version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  core:
    path: ../core
  features:
    path: ../../packages/features
  firebase_adapter:
    path: ../../packages/firebase_adapter
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_storage: ^2.1.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.1
  very_good_analysis: ^9.0.0

flutter:
  generate: true
