name: app_on_riverpod
description: Blueprint app on Riverpod

version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  app_bootstrap:
    path: ../../packages/app_bootstrap
  cached_network_image: ^3.4.1
  core:
    path: ../../packages/core
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  features:
    path: ../../packages/features
  firebase_adapter:
    path: ../../packages/firebase_adapter
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  flutter_riverpod: ^2.6.1
  formz: ^0.8.0
  get_storage: ^2.1.1
  go_router: ^16.2.0
  # hooks_riverpod: ^2.6.1

  # Shared Riverpod-specific utilities for apps using Riverpod
  riverpod_adapter:
    path: ../../packages/riverpod_adapter

  riverpod_annotation: ^2.6.1
  #

dev_dependencies:
  build_runner: ^2.5.4
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.5
  very_good_analysis: ^9.0.0

flutter:
  assets:
    - .env.dev
    - .env.staging
  generate: true
  uses-material-design: true
