name: pub_publish

on:
  push:
    tags:
      # тегуємо з префіксом пакета, напр. core-v1.2.3
      - "core-v[0-9]+.[0-9]+.[0-9]+*"
      - "assets-v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - pkg: core
            path: packages/core
            tag_prefix: core-v
          - pkg: assets
            path: packages/assets
            tag_prefix: assets-v

    steps:
      - uses: actions/checkout@v6

      - uses: dart-lang/setup-dart@v1

      # Пропускаємо дану ітерацію матриці, якщо тег не її префіксу
      - name: Skip if tag doesn't match this matrix
        if: ${{ !startsWith(github.ref_name, matrix.tag_prefix) }}
        run: echo "Tag '${{ github.ref_name }}' doesn't match '${{ matrix.tag_prefix }}'. Skipping."

      - name: Install dependencies
        if: ${{ startsWith(github.ref_name, matrix.tag_prefix) }}
        working-directory: ${{ matrix.path }}
        run: dart pub get

      - name: Publish to pub.dev
        if: ${{ startsWith(github.ref_name, matrix.tag_prefix) }}
        working-directory: ${{ matrix.path }}
        run: dart pub publish --force